### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by OsoaGitHub** [TheEpicBlock/immersive-cursedness#18]
```
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDOUT]: Exception occurred whilst ticking the immersive cursedness thread
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: java.lang.NullPointerException
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.get(MinecraftServer.java:6799)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at dev.hephaestus.fiblib.api.BlockFibRegistry.getBlockState(BlockFibRegistry.java:68)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at net.minecraft.class_2637.fix(class_2637.java:1018)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.handler$bhi000$fixPackets(class_3244.java:4129)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_14364(class_3244.java)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.objects.BlockUpdateMap.lambda$sendTo$0(BlockUpdateMap.java:40)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.Map.forEach(Unknown Source)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.objects.BlockUpdateMap.sendTo(BlockUpdateMap.java:31)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.PlayerManager.tick(PlayerManager.java:159)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.CursednessServer.lambda$tick$1(CursednessServer.java:62)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.HashMap.forEach(Unknown Source)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.CursednessServer.tick(CursednessServer.java:61)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.CursednessServer.start(CursednessServer.java:34)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.ImmersiveCursedness.lambda$onInitialize$0(ImmersiveCursedness.java:23)
[14:27:15] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDOUT]: Exception occurred whilst ticking the immersive cursedness thread
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: java.util.ConcurrentModificationException
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.ArrayList$Itr.next(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at com.google.common.collect.Iterators$3.next(Iterators.java:174)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.Iterator.forEachRemaining(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at net.minecraft.class_1923$1.tryAdvance(class_1923.java:168)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.Spliterator.forEachRemaining(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.PlayerManager.getEntitiesInRange(PlayerManager.java:208)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.PlayerManager.tick(PlayerManager.java:62)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.CursednessServer.lambda$tick$1(CursednessServer.java:62)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.util.HashMap.forEach(Unknown Source)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.CursednessServer.tick(CursednessServer.java:61)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.CursednessServer.start(CursednessServer.java:34)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at nl.theepicblock.immersive_cursedness.ImmersiveCursedness.lambda$onInitialize$0(ImmersiveCursedness.java:23)
[14:28:03] [Immersive Cursedness Thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[14:28:45] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
```

This is also in the logs
`[14:32:14] [Immersive Cursedness Thread/INFO]: [STDOUT]: Exception occurred whilst ticking the immersive cursedness thread
[14:32:14] [Immersive Cursedness Thread/INFO]: [STDERR]: java.lang.NullPointerException`

**Comment by TheEpicBlock** [comment]
I mitigated some of the things shown in the next release. They aren't really important issues and can be ignored unless they spam your console. Thanks for reporting!
