### ISSUE TITLE
Lithium on 1.19.1

### ISSUE THREAD

**Issue by A-Pedraja** [TheEpicBlock/immersive-cursedness#38]
The server goes to time out every time i open a portal
it seems is because of lithium

[22:10:25 WARN] [Immersive Cursedness Thread]: [ImmersiveCursedness] Exception occurred whilst ticking the immersive cursedness thread. This is probably not bad unless it's spamming your console
>....[22:10:25] [Immersive Cursedness Thread/WARN]: Exception occurred whilst ticking the immersive cursedness thread. This is probably not bad unless it's spamming your console
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 131072 out of bounds for length 65537
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 131072 out of bounds for length 65537
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.rehash(Long2ObjectOpenHashMap.java:1341)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.rehash(Long2ObjectOpenHashMap.java:1341)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.insert(Long2ObjectOpenHashMap.java:279)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.insert(Long2ObjectOpenHashMap.java:279)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.put(Long2ObjectOpenHashMap.java:287)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.put(Long2ObjectOpenHashMap.java:287)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at me.jellysquid.mods.lithium.common.util.collections.ListeningLong2ObjectOpenHashMap.put(ListeningLong2ObjectOpenHashMap.java:19)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at me.jellysquid.mods.lithium.common.util.collections.ListeningLong2ObjectOpenHashMap.put(ListeningLong2ObjectOpenHashMap.java:19)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at net.minecraft.class_4180.method_20368(class_4180.java:138)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at net.minecraft.class_4180.method_20368(class_4180.java:138)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at net.minecraft.class_4180.method_19289(class_4180.java:120)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at net.minecraft.class_4180.method_19289(class_4180.java:120)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at net.minecraft.class_4180.getNonEmptyPOISections(class_4180.java:649)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at net.minecraft.class_4180.getNonEmptyPOISections(class_4180.java:649)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at net.minecraft.class_4180.getWithinChunkColumn(class_4180.java:584)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at net.minecraft.class_4180.getWithinChunkColumn(class_4180.java:584)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at net.minecraft.class_4153.method_19123(class_4153.java:561)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at net.minecraft.class_4153.method_19123(class_4153.java:561)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at nl.theepicblock.immersive_cursedness.PortalManager.lambda$getPortalsInChunkRadius$5(PortalManager.java:145)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at nl.theepicblock.immersive_cursedness.PortalManager.lambda$getPortalsInChunkRadius$5(PortalManager.java:145)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at net.minecraft.class_1923$1.tryAdvance(class_1923.java:203)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at net.minecraft.class_1923$1.tryAdvance(class_1923.java:203)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at nl.theepicblock.immersive_cursedness.PortalManager.update(PortalManager.java:37)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at nl.theepicblock.immersive_cursedness.PortalManager.update(PortalManager.java:37)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at nl.theepicblock.immersive_cursedness.PlayerManager.tick(PlayerManager.java:51)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at nl.theepicblock.immersive_cursedness.PlayerManager.tick(PlayerManager.java:51)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at nl.theepicblock.immersive_cursedness.CursednessServer.lambda$tick$1(CursednessServer.java:65)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at nl.theepicblock.immersive_cursedness.CursednessServer.lambda$tick$1(CursednessServer.java:65)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.util.HashMap.forEach(HashMap.java:1421)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at nl.theepicblock.immersive_cursedness.CursednessServer.tick(CursednessServer.java:64)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at nl.theepicblock.immersive_cursedness.CursednessServer.tick(CursednessServer.java:64)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at nl.theepicblock.immersive_cursedness.CursednessServer.start(CursednessServer.java:36)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at nl.theepicblock.immersive_cursedness.CursednessServer.start(CursednessServer.java:36)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at nl.theepicblock.immersive_cursedness.ImmersiveCursedness.lambda$onInitialize$0(ImmersiveCursedness.java:26)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at nl.theepicblock.immersive_cursedness.ImmersiveCursedness.lambda$onInitialize$0(ImmersiveCursedness.java:26)
[22:10:25 INFO] [Immersive Cursedness Thread]: [LoggedPrintStream] [STDERR]:    at java.base/java.lang.Thread.run(Thread.java:833)
>....[22:10:25] [Immersive Cursedness Thread/INFO]: [STDERR]:   at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by popos123** [comment]
nope, i have the same with only this mod on the server side
